Repository RollForGuild/TheGM, pull requests merged in 2018-02, with the labels that each got.

#35 Add endpoint to validate a session
  web/controllers/sessions_controller.ex
  web/router.ex
Labels: enhancement

#34 Feature password reset
  priv/repo/migrations/20180209122027_add_password_reset_table.exs
  resources/password_reset_email.html
  web/Mailgun.ex
  web/controllers/passwordresets_controller.ex
  web/models/passwordresets.ex
  web/router.ex
Labels: enhancement

#39 Add distance to groups in search
  web/views/groups_view.ex
Labels: bug

#61 30/feature update group
  web/controllers/groups_controller.ex
  web/models/groups.ex
Labels: bug

#63 Rewrite groups controller to use common function for displaying member status
  web/controllers/groups_controller.ex
  web/models/groups.ex
  web/views/groups_view.ex
Labels: bug

#65 Fix group creation failing and member_status not returning correct value
  web/controllers/groups_controller.ex
  web/models/groups.ex
  web/views/groups_view.ex
Labels: blocker, bug

#62 Implement ability for a user to leave a group or for group admin to remove a user
  web/controllers/groupjoinrequests_controller.ex
  web/controllers/groupmembers_controller.ex
  web/router.ex
Labels: enhancement
